//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp_testConcurrent.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Setconnection2p", ReplyAction="http://tempuri.org/IService1/Setconnection2pResponse")]
        System.Collections.Generic.Queue<string> Setconnection2p(string k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Setconnection2p", ReplyAction="http://tempuri.org/IService1/Setconnection2pResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Queue<string>> Setconnection2pAsync(string k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkPlayers", ReplyAction="http://tempuri.org/IService1/checkPlayersResponse")]
        System.Collections.Generic.Queue<string> checkPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkPlayers", ReplyAction="http://tempuri.org/IService1/checkPlayersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Queue<string>> checkPlayersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApp_testConcurrent.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApp_testConcurrent.ServiceReference1.IService1>, ConsoleApp_testConcurrent.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Collections.Generic.Queue<string> Setconnection2p(string k) {
            return base.Channel.Setconnection2p(k);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Queue<string>> Setconnection2pAsync(string k) {
            return base.Channel.Setconnection2pAsync(k);
        }
        
        public System.Collections.Generic.Queue<string> checkPlayers() {
            return base.Channel.checkPlayers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Queue<string>> checkPlayersAsync() {
            return base.Channel.checkPlayersAsync();
        }
    }
}
